#!/usr/bin/env bash
# How to Install and Configure UFW
sudo apt-get update -y
sudo apt-get install ufw -y
sudo ufw disable
sudo ufw default deny incoming
sudo ufw allow ssh/tcp
sudo ufw allow http/tcp
sudo ufw allow https/tcp
sudo ufw enable
sudo service ufw start
